function main()
clear all;clc;
addpath('/data/srb1/wchen/tools/m_fx/','-end')
yyyy   = 2000;

mntt   = 15 ;
tR     = 3  ;

stid   = 'bon';
EMIS   = 0.97;
pthin  = '/data/ceop4/srb/SURFRAD/2000/';
pthout = '/data/srb3/wchen/LST/SURFRAD_obtained/2000_LST_SURFRAD_BON_UTC00-23.dat'
 
 dw_ir = extract_hourly_specific_mnt(pthin,stid,yyyy,mntt,tR,17); % column 17 : dw_ir; column 23: up_ir
 up_ir = extract_hourly_specific_mnt(pthin,stid,yyyy,mntt,tR,23);
 const = 5.670373e-8;
 
 exps1 = up_ir-(1-EMIS)*dw_ir;
 exps2 = const*EMIS;
 exps  = exps1/exps2;
 LST   = exps.^0.25;
 LST   = LST(:);
 LST(find(isnan(LST)))= -9999.9;
 fid   = fopen(pthout,'w')
 fwrite(fid,LST,'float32')
 fclose(fid) 
  
end
%************************************************************************
function dataout=extract_hourly_specific_mnt(pthin,stid,yyyy,mntt,tR,Cn)
%************************************************************************
%---------------------------------------------- 
% pthin -- input data path
% stid  -- station id
% yyyy  -- year
% mntt  -- the minute needs to be extracted
% tR    -- temperal radius
% Cn-- column number
%----------------------------------------------
yearstr    = num2str(yyyy);
yystr      = yearstr(3:4);
if yyyy<2009
   tRes    = 3;
else
   tRes    = 1;
end
if leapyear(yyyy)
    ndays  = 366;
else
    ndays  = 365;
end
nhor   = 24;
dataout = nan(nhor,ndays);
for jday = 1:ndays
   %disp(jday)
    dystr    = num2str(jday,'%03d');
    filename =[pthin,stid,yystr,dystr,'.dat'];
    if exist(filename)
        datain   = importfile(filename);
        mnt      = datain(:,6); % column 6 is minute after hour
        inds     = find(mnt==mntt);  
       %disp(length(inds)) 
        var      = datain(:,Cn); 
        var(var<-9000.) = NaN;
       if length(inds)==nhor
        for ihor = 1:nhor
            indstrt = inds(ihor)-tR/tRes; %5;
            indend  = inds(ihor)+tR/tRes; %5;          
            if indstrt<1
               indstrt=1;
            end % if indstrt
            if indend>length(mnt)
                indend = length(mnt);
            end % if indend
            tmp  = var(indstrt:indend);
            tmp  = nanmean(tmp);
            dataout(ihor,jday) = tmp;
        end %for ihor
       else
         disp(['day of year ',num2str(jday),'has missing hours'])
       end          
     else
        disp([filename,'does not exist'])
    end % if exist
 
end % for jday
end



function data=importfile(fileToRead)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 04-Aug-2015 14:38:00

DELIMITER = ' ';
HEADERLINES = 2;

% Import the file
newData = importdata(fileToRead, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData);
data = newData.data ;

end

